import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { Subtitle } from "./components/Subtitle";
import { RateToggle, RATE_MIN, RATE_MAX } from "./components/RateToggle";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

const RATE_STORAGE_KEY = "presentation-playback-rate";

function clampRate(n: number): number {
  if (!Number.isFinite(n)) return 1;
  return Math.max(RATE_MIN, Math.min(RATE_MAX, n));
}

function loadRate(): number {
  if (typeof window === "undefined") return 1;
  const raw = window.localStorage.getItem(RATE_STORAGE_KEY);
  return clampRate(raw ? Number(raw) : 1);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  const [rate, setRate] = useState<number>(loadRate);
  const handleRateChange = useCallback((next: number) => {
    const clamped = clampRate(next);
    setRate(clamped);
    try {
      window.localStorage.setItem(RATE_STORAGE_KEY, String(clamped));
    } catch {
      /* localStorage may be unavailable (private mode) — ignore */
    }
  }, []);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  // Cache-busting: hash the narration text so browsers refetch on re-synth.
  const audioFingerprint = stepText
    ? (stepText.length * 31 + stepText.charCodeAt(0) + (stepText.charCodeAt(stepText.length - 1) || 0)).toString(36)
    : "0";
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3?v=${audioFingerprint}`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  const audioProgress = useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    playbackRate: rate,
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
        <Subtitle
          text={stepText}
          currentTime={audioProgress.currentTime}
          duration={audioProgress.duration}
        />
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <RateToggle rate={rate} onChange={handleRateChange} />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
