import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useMemo, useState } from "react";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { Subtitle } from "./components/Subtitle";
import { VideoControls } from "./components/VideoControls";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import audioDurations from "./registry/audio-durations.json";

const RATE_MIN = 1.0;
const RATE_MAX = 2.0;
const RATE_STEP = 0.05;

const RATE_STORAGE_KEY = "presentation-playback-rate";
const PAUSED_STORAGE_KEY = "presentation-paused";

function clampRate(n: number): number {
  if (!Number.isFinite(n)) return 1;
  return Math.max(RATE_MIN, Math.min(RATE_MAX, n));
}

function loadRate(): number {
  if (typeof window === "undefined") return 1;
  const raw = window.localStorage.getItem(RATE_STORAGE_KEY);
  return clampRate(raw ? Number(raw) : 1);
}

/**
 * Estimate a step's duration in seconds when we don't have a measured mp3
 * length (e.g. empty narration, audio file missing). Chinese TTS at +20%
 * lands near 5 chars/second, so 0.2s per character is a fair fallback.
 */
function estimateStepSeconds(text: string): number {
  if (!text) return 1.5;
  return Math.max(1.5, text.length * 0.2);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // Build a flat timeline mapping (globalIdx → step duration). audio-durations.json
  // ships from measure-audio.ts and falls back to the char-count estimate for any
  // missing entries (e.g. new chapter added but not yet resynthesized).
  const { stepStarts, totalDuration } = useMemo(() => {
    const starts: number[] = [];
    let acc = 0;
    const dict = audioDurations as Record<string, Record<string, number>>;
    for (const c of CHAPTERS) {
      const chDict = dict[c.id] ?? {};
      c.narrations.forEach((text, i) => {
        const measured = chDict[String(i + 1)];
        const d = measured && measured > 0 ? measured : estimateStepSeconds(text);
        starts.push(acc);
        acc += d;
      });
    }
    return { stepStarts: starts, totalDuration: acc };
  }, []);

  const [rate, setRate] = useState<number>(loadRate);
  const [paused, setPaused] = useState<boolean>(() => {
    if (typeof window === "undefined") return false;
    return window.localStorage.getItem(PAUSED_STORAGE_KEY) === "1";
  });

  const handleRateChange = useCallback((next: number) => {
    const clamped = clampRate(next);
    setRate(clamped);
    try {
      window.localStorage.setItem(RATE_STORAGE_KEY, String(clamped));
    } catch {
      /* ignore */
    }
  }, []);

  const handleTogglePlay = useCallback(() => {
    setPaused((p) => {
      const next = !p;
      try {
        window.localStorage.setItem(PAUSED_STORAGE_KEY, next ? "1" : "0");
      } catch {
        /* ignore */
      }
      return next;
    });
  }, []);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  const audioFingerprint = stepText
    ? (stepText.length * 31 + stepText.charCodeAt(0) + (stepText.charCodeAt(stepText.length - 1) || 0)).toString(36)
    : "0";
  const audioSrc =
    stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3?v=${audioFingerprint}`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  const player = useAudioPlayer({
    src: audioSrc,
    mode: "auto",
    trailMs: 200,
    estimateFallbackMs: Math.round(estimateStepSeconds(stepText) * 1000),
    playbackRate: rate,
    paused,
    onAutoAdvance,
    autoStarted: true,
  });

  // Compute global time = (start time of current step) + audio.currentTime
  const currentStart = stepStarts[stepper.globalIndex] ?? 0;
  const currentGlobalTime = currentStart + player.currentTime;

  const handleSeek = useCallback(
    (seconds: number) => {
      const target = Math.max(0, Math.min(seconds, totalDuration - 0.01));
      // Find which step covers `target`. stepStarts is monotonically increasing.
      let lo = 0;
      let hi = stepStarts.length - 1;
      while (lo < hi) {
        const mid = (lo + hi + 1) >> 1;
        if (stepStarts[mid]! <= target) lo = mid;
        else hi = mid - 1;
      }
      const globalIdx = lo;
      const internal = target - (stepStarts[globalIdx] ?? 0);

      if (globalIdx !== stepper.globalIndex) {
        stepper.jumpToGlobal(globalIdx);
        // The audio src will change on next render — useAudioPlayer queues this
        // seek and consumes it on `loadedmetadata`.
        player.seek(internal);
      } else {
        // Same step — seek within the current audio element immediately.
        player.seek(internal);
      }
    },
    [stepStarts, totalDuration, stepper, player],
  );

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
        <Subtitle
          text={stepText}
          currentTime={player.currentTime}
          duration={player.duration}
        />
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <VideoControls
        currentTime={currentGlobalTime}
        totalDuration={totalDuration}
        playing={!paused && player.playing}
        rate={rate}
        rateMin={RATE_MIN}
        rateMax={RATE_MAX}
        rateStep={RATE_STEP}
        onTogglePlay={handleTogglePlay}
        onSeek={handleSeek}
        onRateChange={handleRateChange}
      />
    </>
  );
}
